server:
  port: 9900

spring:
  rabbitmq:
    host: 81.71.92.103
    port: 5672
    username: ems
    password: ems
    virtual-host: /ems

  application:
    name: CONFIGSERVER
  cloud:
    config:
      #远程仓库地址
      server:
        git:
          uri: https://gitee.com/AgMonk/cloud_configs.git
          default-label: master
          username: AgMonk
          password: dzkjd719
    consul:
      host: localhost
      port: 8500

management:
  endpoints:
    web:
      exposure:
        include: '*'