server:
  port: 9500

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: category_router
          uri: lb://CATEGORY
          predicates:
            - Path=/category
        - id: product_router
          uri: lb://PRODUCT
          predicates:
            - Path=/product
  application:
    name: GATEWAY
