eureka:
  client:
    #不立即注册
    fetch-registry: false
  #不注册为客户端
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
#    register-with-eureka: false
spring:
  profiles:
    active: server-1
  application:
    name: eureka-server