server:
  port: 8890

spring:
  application:
    name: USERS
  cloud:
    consul:
      host: localhost
      port: 8500

#ORDERS:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
